/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/CD0HE7EKK5O
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"

function generateRandomName() {
    const names = [
        "Alice",
        "Bob",
        "Charlie",
        "David",
        "Evie",
        "Frank",
        "Grace",
        "Hannah",
        "Isaac",
        "Jack",
        "Katie",
        "Liam",
        "Mia",
        "Nathan",
        "Olivia",
        "Peter",
        "Quinn",
        "Rachel",
        "Sam",
        "Tina",
        "Ulysses",
        "Victoria",
        "Will",
        "Xavier",
        "Yasmin",
        "Zach"
    ]

    const randomIndex = Math.floor(Math.random() * names.length)

    return names[randomIndex]
}

export const Welcome = ({ onNameSubmit }) => {
  const [name, setName] = useState("")
  const handleRandomName = () => {
    const randomName = generateRandomName()
    setName(randomName)
  }

  const handleKeyDown = (e) => {
    if (e.key === 'Enter') {
      handleSubmit();
    }
  };

  const handleSubmit = () => {
    if (name.trim()) {
      onNameSubmit(name);
    }
  };

  return (
    <div className="flex items-center justify-center h-screen">
      <div className="bg-background p-8 md:px-32 rounded-lg shadow-lg md:max-w-xl lg:max-w-3xl space-y-4 text-center">
        <h1 className="text-4xl font-bold">Can you eat AI for breakfast?</h1>

          <p className="text-muted-foreground">
            Prove yourself against state of the art AI models in games of strategy, deduction, and deception.
          </p>

        <h2 className="text-xl font-bold">Enter your name to begin</h2>
        <div className="space-y-4 md:w-4/5 mx-auto">
            <div className="flex items-center">
              <Input
                id="name"
                placeholder="Enter your name"
                className="w-full"
                value={name}
                onChange={(e) => setName(e.target.value)}
                onKeyDown={handleKeyDown}
              />
                <TooltipProvider>
                  <Tooltip>
                    <TooltipTrigger asChild>
                      <Button variant="ghost" size="icon" className="ml-2" onClick={handleRandomName}>
                        <ShuffleIcon className="w-4 h-4" />
                        <span className="sr-only">Random Name</span>
                      </Button>
                    </TooltipTrigger>
                    <TooltipContent>
                      <p>Random Name</p>
                    </TooltipContent>
                  </Tooltip>
                </TooltipProvider>
            </div>
            <Button disabled={!name} className="flex items-center justify-center w-full mx-auto px-8" onClick={handleSubmit}>
                Start Game
            </Button>
        </div>


      </div>
    </div>
  )
}

function ShuffleIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 18h1.4c1.3 0 2.5-.6 3.3-1.7l6.1-8.6c.7-1.1 2-1.7 3.3-1.7H22" />
      <path d="m18 2 4 4-4 4" />
      <path d="M2 6h1.9c1.5 0 2.9.9 3.6 2.2" />
      <path d="M22 18h-5.9c-1.3 0-2.6-.7-3.3-1.8l-.5-.8" />
      <path d="m18 14 4 4-4 4" />
    </svg>
  )
}
